### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by carrie0307** [PlusLabNLP/ESTER#1]
Hello, 
    Thanks for your released source code. However, I met an error as follows when I ran run_span_pred.py:
    
    File "/home/cuishiyao/ESTER-master/code/utils.py", line 198, in filter_outputs
    filtered_logits.append(logits[b, offset[i], :].unsqueeze(0))
IndexError: index 320 is out of bounds for dimension 1 with size 320

    I am looking forward to your early reply!

**Comment by rujunhan** [comment]
hello, did you follow our instruction by running run_span_pred.sh? max_seq_len should be set there.
